Import libraries and import dataset
X stores Counrty, Age, and Salary
Y stores purchased 

In [31]:
import numpy as np
import pandas as pd

df = pd.read_csv('../datasets/Data.csv')

X = df.iloc[ : , :-1].values
Y = df.iloc[ : , 3].values


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Handling missing data

Common practices
    - Filling in NaN values with the average or mean
        - Imputer: imputation transformer that completes missing values


In [25]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")
imputer = imputer.fit(X[ : , 1:3])
X[ : , 1:3] = imputer.transform(X[ : , 1:3])

Encoding categorical data
    - Changes name of countries to integer representation

In [26]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

label_X = LabelEncoder()
X[:,0] = label_X.fit_transform(X[:,0])

print(X)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


Creating dummy Variable

In [27]:
hot_encoder = OneHotEncoder()
X = hot_encoder.fit_transform(X).toarray()
print(X)
label_Y = LabelEncoder()
Y = label_Y.fit_transform(Y)
print(Y)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
[0 1 0 0 1 1 0 1 0 1]


Training Sets and Test Sets

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = .2, random_state = 0)
print(X_train, X_test)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]] [[0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Feature Scaling

In [29]:
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

print(X_train)

[[-1.          2.64575131 -0.77459667 -0.37796447  0.         -0.37796447
  -0.37796447 -0.37796447 -0.37796447  2.64575131 -0.37796447 -0.37796447
   0.         -0.37796447 -0.37796447  0.         -0.37796447 -0.37796447
   2.64575131 -0.37796447 -0.37796447 -0.37796447  0.        ]
 [ 1.         -0.37796447 -0.77459667 -0.37796447  0.         -0.37796447
   2.64575131 -0.37796447 -0.37796447 -0.37796447 -0.37796447 -0.37796447
   0.         -0.37796447 -0.37796447  0.         -0.37796447 -0.37796447
  -0.37796447  2.64575131 -0.37796447 -0.37796447  0.        ]
 [-1.         -0.37796447  1.29099445  2.64575131  0.         -0.37796447
  -0.37796447 -0.37796447 -0.37796447 -0.37796447 -0.37796447 -0.37796447
   0.          2.64575131 -0.37796447  0.         -0.37796447 -0.37796447
  -0.37796447 -0.37796447 -0.37796447 -0.37796447  0.        ]
 [-1.         -0.37796447  1.29099445 -0.37796447  0.         -0.37796447
  -0.37796447 -0.37796447  2.64575131 -0.37796447 -0.37796447 -0.377964